### ISSUE TITLE
Improve the test code

### ISSUE THREAD

**Issue by Aiskorim** [AlessiaGava/Final-Crewmates-Project-#10]
Check the code of the tests and improve it

**Comment by Atrus33** [comment]
Can you be a little more specific? thanks

**Comment by Aiskorim** [comment]
I have created the tests for the Main.py file in the ui_main branch. 
In my local branch, I tested the file, but the result is a loop of inputs until it quits as I insert "Q" as input.
I need help to check what is wrong.

**Comment by Atrus33** [comment]
The normal behavior of the code is: loop until you type Q, so the results you get are normal. In any case even with this structure, unittest will provide you with test results at the end of the program (when you enter Q).
