### ISSUE TITLE
Comment in a more detailed way Functions.py

### ISSUE THREAD

**Issue by Aiskorim** [AlessiaGava/Final-Crewmates-Project-#12]
In the branch name_function, leave more detailed documentation and comments for the document Funtions.py

**Comment by alessiazhou** [comment]
I added comment to the functions 0c4ab20ff87a8fc6de13f1fcbfcd05e1c7c1709f

**Comment by AlessiaGava** [comment]
Closed in d2471ac317b6f50e6b7d761e262bf4058dfc7941.
