### ISSUE TITLE
Create branch develop

### ISSUE THREAD

**Issue by sofijackson** [AlessiaGava/Final-Crewmates-Project-#3]

**Comment by Atrus33** [comment]
:heavy_exclamation_mark: Remember everyone, **merge only on this branch**, and do **not carry on the main before luisa has tested everything** :heavy_exclamation_mark:

**Comment by sofijackson** [comment]
I have already created the branch "develop" but we pinned it to remember to merge our files with this branch until @Aiskorim has tested everything.
